inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AsciiComments: #日本語手のコメントを許可する
  Enabled: false

Documentation: #クラスにコメントを記載しなくても良い
  Enabled: false

ClassAndModuleChildren: #モジュール名::クラス名の定義を許可する
  Enabled: false

Style/FrozenStringLiteralComment: # 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
  Enabled: false
  
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    
Rails/InverseOf:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/like.rb'

Layout/LineLength:
  Max: 160

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/requests/users_request_spec.rb'

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20200804030726_add_column_to_post.rb'
    