version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
      MYSQL_DATABASE: ramen_master_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/ramen_master
      - public-data:/ramen_master/public
      - tmp-data:/ramen_master/tmp
      - log-data:/ramen_master/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/ramen_master/public
      - tmp-data:/ramen_master/tmp
    ports:
      - 80:80

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data: