development:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: db
  database: ramen_master_devlopment

test:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: db
  database: ramen_master_test

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ramen_master
  pool: 5
  username: masaya
  password: lovewhat
  socket: /var/lib/mysql/mysql.sock
  host: ramen-master-mysql.ctingpvpbrhg.ap-northeast-1.rds.amazonaws.com
  database: ramen_master_production