default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ramen_master
  pool: 5
  username: masaya
  password: lovewhat
  socket: /var/lib/mysql/mysql.sock
  host: ramen-master-mysql.ctingpvpbrhg.ap-northeast-1.rds.amazonaws.com

development:
  <<: *default
  database: ramen_master_devlopment

test:
  <<: *default
  database: ramen_master_test

production:
  <<: *default
  database: ramen_master_production